### ISSUE TITLE
Honeypot fields only work with CSP "unsafe-inline"

### ISSUE THREAD

**Issue by brickcamp** [Hazzeldorn/HazzelForms#1]
HI there,

thanks a lot for this piece of software. I noticed that honeypot fields can't be combined with a strict Content Security Policy on "style-src", because they add Inline-CSS.

Maybe it would be better, if one could add custom CSS classes (similar to normal fields) and disable inline CSS via another parameter:

```
$form->addField('Pseudo-Captcha',  'honeypot', ['classlist' => 'undercover',
                                                'no-css'    => true ]);
```

This would also make it harder for bots as every page can have their own way of hiding the honeypots. :slightly_smiling_face:

**Comment by Hazzeldorn** [comment]
Hi Tobias
Thanks a lot for this suggestion. 👍 

At the moment you are able to use CSP with a normal text field matching against a regular expression that only allows empty strings. Add something like that to the params: `'regex' => '/^\A\z$/'`
But its a bit a hack...

I will release a new version with your proposed changes by the end of the week :)

**Comment by Hazzeldorn** [comment]
Hey @brickcamp 

The [version 1.2.4](https://github.com/Hazzeldorn/HazzelForms/releases/tag/1.2.4) is now compatible with strict Content Security Policies:
```
$form->addField('Pseudo-Captcha', 'honeypot', [
	'classlist' => 'undercover',
	'inline-css' => false
])
```
You'll need to hide the honeypot field within the external stylesheet:
```
.undercover {
	display: none !important;
}
```

Happy coding! 🤓

**Comment by brickcamp** [comment]
Thanks a lot :slightly_smiling_face:
